### ISSUE TITLE
Media Monkey 5.0.0.2338? SongsDB5.SDBApplication

### ISSUE THREAD

**Issue by Mist-Hunter** [patzm/plex-music-rating-sync#20]
Hello,

Thank you for this great software, I'm sure this is user error on my part, but I keep getting this error with Media Monkey 5.0.0.2338

**[PlexSync.MediaMonkey.connect:135] No scripting interface to MediaMonkey can be found. Exiting...**

I don't see anything special in the instructions pertaining to MediaMonkey setup requirements, but I did see this link:
https://www.mediamonkey.com/wiki/Controlling_MM5_from_External_Applications

> The SDBApplication class is largely unchanged from MediaMonkey 4, but the biggest difference is that it is named SongsDB5.SDBApplication instead of SongsDB.SDBApplication.

I notice the MediaPlayer.py, line 132, references the "SongsDB.SDBApplication" class (?), but simply editing it to "SongsDB**5**.SDBApplication" just threw different errors. This is all probably a red-herring covering up something obvious I'm missing, but I thought I'd drop it here in case.

**Comment by patzm** [comment]
closed with #26
