### ISSUE TITLE
Bidirectional sync to tags?

### ISSUE THREAD

**Issue by wcsherrod** [patzm/plex-music-rating-sync#22]
Any plans to include this feature? Are there any existing tools that can allow for this?

**Comment by smilerz** [comment]
@wcsherrod the current version can sync in both directions (configurable in config.ini as well as at command line) and now also includes methods to address conflicting ratings.

I am not planning on working on true bi-directional and I don't think the main contributor is either as the current functionality works well enough for my use case.

**Comment by wcsherrod** [comment]
That is good to know, thanks. What is the difference between what it can do now and "true" bidirectional sync? Do you mean that it will sync to the player (e.g. MusicBee) but not to the individual file tags and then the player would have to be set up to write the ratings to the files later?

**Comment by smilerz** [comment]
I guess I'd say true bidirectional would be that it looked at both sides and sync ratings in whichever direction is necessary.

Now you have to sync Plex -> MM and then MM -> Plex.  So a 2-step process as opposed to a 1-step process.

**Comment by wcsherrod** [comment]
That is good to know, thanks. What is the difference between what it can do now and "true" bidirectional sync? Do you mean that it will sync to the player (e.g. MusicBee) but not to the individual file tags and then the player would have to be set up to write the ratings to the files later?
