### ISSUE TITLE
No scripting interface to MediaMonkey

### ISSUE THREAD

**Issue by Benjamen1** [patzm/plex-music-rating-sync#23]
Hi trying to get this to work with my library, does MediaMonkey need to be configured at all? I moved the installation of MediaMonkey back to my V: drive where the github repo is but not sure if this makes a difference. Can you assist? 

|![image](https://user-images.githubusercontent.com/18605165/128590643-3ccbf6e4-79a2-43d8-9e20-9c42ab2fa433.png)

**Comment by patzm** [comment]
Sorry I never had that issue. Which MediaMonkey version are you running? And did you properly install it with a install wizard or simply run the `.exe`?

**Comment by Benjamen1** [comment]
> Sorry I never had that issue. Which MediaMonkey version are you running? And did you properly install it with a install wizard or simply run the `.exe`?

Version 5.0, it's installed. Not portable.

**Comment by smilerz** [comment]
Looks like they only are going to partially support COM on MM5 and may not at all on future versions.

Try this, if that doesn't work I'd install MM4.
![image](https://user-images.githubusercontent.com/1808639/128599712-fd360df8-c755-4672-b8a1-69dec44fe5f2.png)

**Comment by Benjamen1** [comment]
Yeah that has fixed that issue, installed and am now using MediaMonkey V4
Getting an issue with it not finding a certain playlist. 

![image](https://user-images.githubusercontent.com/18605165/128618241-9bccd819-ba97-42e6-aa1d-0cf8601d26f2.png)
![image](https://user-images.githubusercontent.com/18605165/128618242-535b4acf-18da-4d3c-9a48-07909fe58ee8.png)

**Comment by Benjamen1** [comment]
Apologies might have misread, not sure if you can sync individual playlists. I've tried the parameter "tracks"

![image](https://user-images.githubusercontent.com/18605165/128618518-006f80d6-da9d-427e-b8e9-6a07a8775f02.png)

**Comment by Benjamen1** [comment]
> 
> 
> Apologies might have misread, not sure if you can sync individual playlists. I've tried the parameter "tracks"
> 
> ![image](https://user-images.githubusercontent.com/18605165/128618518-006f80d6-da9d-427e-b8e9-6a07a8775f02.png)

#21 Solves this

**Comment by Benjamen1** [comment]
different issue but thought easier to reply to this thread.

![image](https://user-images.githubusercontent.com/18605165/128626386-1784f50d-2782-432c-a02a-e068b20b20f8.png)

**Comment by patzm** [comment]
#24 closed #21, now working on the second issue you reported

**Comment by patzm** [comment]
Can you search post the command you used to run the last sync that crashed?
My assumption is that you have a track without a title. Can you run the same command you have again with this commit ed66cfc06a023f745ab54cc2083caa7e8cebb0e3 or the latest state of the branch `martin/fix/matches-referenced`?

**Comment by Benjamen1** [comment]
`sync_ratings.py --server plexberry2 --username <my username> --token <my token>  --sync tracks --dry`

**Comment by Benjamen1** [comment]
`sync_ratings.py --server plexberry2 --username <my username> --token <my token> --sync tracks --dry`

Reran with new branch
![image](https://user-images.githubusercontent.com/18605165/128694962-391344ac-d4b0-4897-a0ca-f258c1a835f3.png)


could possibly be a track without a title.

**Comment by patzm** [comment]
ok I made a refactoring bug, can you try with 100933638f233f88e18ede43678c6aae0cf715cd?

**Comment by Benjamen1** [comment]
Yep was a track with no name, not sure which one as my library collection is extensive.

![image](https://user-images.githubusercontent.com/18605165/128707131-dfb09daa-cbe3-4cff-ac33-203ba987f522.png)

**Comment by smilerz** [comment]
Go to the track view in Plex and sort by Title.  The empty ones should be at the top (or bottom).

**Comment by patzm** [comment]
ok glad to hear. So to close this issue @Benjamen1, can you clarify: did the scripting interface for MediaMonkey 5 work or not? In https://github.com/patzm/plex-music-rating-sync/issues/23#issuecomment-894730489 it sounds like it, but then i don't understand why you reverted back to MediaMonkey 4 after all :confused:.
If MediaMonkey 5 doesn't work, then we should update the readme.

**Comment by Benjamen1** [comment]
![image](https://user-images.githubusercontent.com/18605165/128709609-ced2355b-53db-48d0-9adb-d8e06d1993c9.png)

![image](https://user-images.githubusercontent.com/18605165/128709742-426cd3b2-7d43-47fc-aea3-9b6a85f5df9c.png)

Track view shows these two but no tracks with no names? Does plex show tracks which it cant match?

**Comment by Benjamen1** [comment]
> 
> 
> ok glad to hear. So to close this issue @Benjamen1, can you clarify: did the scripting interface for MediaMonkey 5 work or not? In [#23 (comment)](https://github.com/patzm/plex-music-rating-sync/issues/23#issuecomment-894730489) it sounds like it, but then i don't understand why you reverted back to MediaMonkey 4 after all 😕.
> If MediaMonkey 5 doesn't work, then we should update the readme.

I installed MediaMonkey v4 because yeah MM5 doesn't work.

**Comment by Benjamen1** [comment]
Happy to close this issue as the original issue was resolved with #26 and Issue Tracks without title #25 has been opened

**Comment by Conza88** [comment]
> Looks like they only are going to partially support COM on MM5 and may not at all on future versions.
> 
> Try this, if that doesn't work I'd install MM4.

Is this still the case?
