### ISSUE TITLE
tracks without title

### ISSUE THREAD

**Issue by patzm** [patzm/plex-music-rating-sync#25]
![image](https://user-images.githubusercontent.com/18605165/128709609-ced2355b-53db-48d0-9adb-d8e06d1993c9.png)

![image](https://user-images.githubusercontent.com/18605165/128709742-426cd3b2-7d43-47fc-aea3-9b6a85f5df9c.png)

Track view shows these two but no tracks with no names? Does plex show tracks which it cant match?

_Originally posted by @Benjamen1 in https://github.com/patzm/plex-music-rating-sync/issues/23#issuecomment-895200142_

**Comment by patzm** [comment]
To debug this, can you try 5e9b6f08040e5ab625945bb51ccfac9379f13f67.

**Comment by Benjamen1** [comment]
There is an indention error on 99,
![image](https://user-images.githubusercontent.com/18605165/128712909-0c6b401f-d11c-4acd-8b0d-035129fde595.png)


 quickly fixed and re-ran
 
 
![image](https://user-images.githubusercontent.com/18605165/128713046-172790a9-19be-4055-b9ec-a9f60a3a8ac6.png)


Your try catch was clever, but my poorly managed library was smarter haha, somewhere I have a track with the values - and -.

**Comment by smilerz** [comment]
if you run with --log DEBUG you can see what processes prior to failure.  That should give you a clue as to where to look.

**Comment by Benjamen1** [comment]
Found the track causing the issue and reran the script. Seems to be getting past this point now and reading in the tracks with their ratings. Going to let it run and ill keep you guys updated on the results. Vielen Dank

**Comment by smilerz** [comment]
> Your try catch was clever, but my poorly managed library was smarter haha, somewhere I have a track with the values - and -.

@patzm is the file path available in the Plex API?  That might be an alternative way to catch an offending source.

**Comment by patzm** [comment]
Ok first of all thanks for the tab fix... Switching between editors... I commited it now to 96f32ed8fd9992e72ec9da0cd7386512f8ab5d4f. @smilerz we should migrate to 4-spaces convention if you don't mind. That is more of a standard. I got to like `black` in the past.

Your print statement `Failed to search tracks for track  -  - .` means that all three fields https://github.com/patzm/plex-music-rating-sync/blob/6a01ca488648c35385f87e7f316190317c6c53f1/sync_items.py#L9-L11 are not set.

I added printing the local file path as well in a1dcd16fd97404d5eb76d10ae22b1a07def7f3e0 now. Note that I didn't test any of this, as I am not actively using the code base anymore. So great if you can fix things on the fly as earlier. You can also start contributing to the repo directly if you want, @Benjamen1. Then I make a contributor.

**Comment by Benjamen1** [comment]
More than welcome, thank you for your constant support. Thanks, ill have a poke around the code and see if I can make some helpful changes. I am currently in the process of cleaning up my library and will resync when I have the library in a good state. One quick question before I start doing too many clean up activities. How does the sync match songs from MediaMonkey to Plex, like is it simply the title of the song? or a combination of several of fields or something else?

**Comment by patzm** [comment]
> How does the sync match songs from MediaMonkey to Plex, like is it simply the title of the song? or a combination of several of fields or something else?

Yes, combination of the following:
https://github.com/patzm/plex-music-rating-sync/blob/6a01ca488648c35385f87e7f316190317c6c53f1/sync_pair.py#L199-L211
