### ISSUE TITLE
ERROR [PlexSync.PlexPlayer.connect:297] Error: Unable to connect

### ISSUE THREAD

**Issue by slydog3333** [patzm/plex-music-rating-sync#30]
I think I've got it all setup right but I'm getting this error when using the api token or when using the password.

I get a different message if the password is wrong so I assume it's connecting somewhat.

Seperate question does this get ratings from voribis comments in flac files? I see you only mention ID3 which is used in MP3's.

**Comment by slydog3333** [comment]
Figured out my issue was that my server wasn't the name of my username, I had named it Server. Once I changed that, I got connected.

And It does work for FLAC files.

Thank you so much for this script. It makes Plexamp useful now.

**Comment by patzm** [comment]
awesome, great to hear that 👍.

**Comment by slydog3333** [comment]
Do you think it's possible to sync mood and occasion?
  

  

  
  
 Jeff
      
  
  
>

**Comment by patzm** [comment]
Well if these two attributes are accessible in MediaMonkey too, why not. Feel free to fork, try, and open a PR 😉
