### ISSUE TITLE
MediaMonkey to Plex on NAS

### ISSUE THREAD

**Issue by Paulus237** [patzm/plex-music-rating-sync#32]
Hello, can I run this on my PC where Mediamonkey resides and output to Plex on my Nas on the network?

**Comment by patzm** [comment]
Yes no problem.

See the [readme](https://github.com/patzm/plex-music-rating-sync?tab=readme-ov-file#how-to-run): the server name and your username must be registered with Plex, and your Plex server must be visible on the internet. So basically: if your mobile app or https://app.plex.tv can reach the server without the warning that it is not accessible, then the rating sync will work as well.

**Comment by Paulus237** [comment]
Thank you for quickly responding. I'm a beginner here at scripts, etc. It's been a journey installing all the requirements ;-)
I think I'm all set but not getting any log output to test my script. When I run sync_ratings.py a new window opens and closes very quickly...I have edited the config with my settings, but tbh I have no idea I've done that correctly eg. line one is:
#server = 		#Elvidge+

Thank you for your patience!

**Comment by smilerz** [comment]
> Thank you for quickly responding. I'm a beginner here at scripts, etc. It's been a journey installing all the requirements ;-) I think I'm all set but not getting any log output to test my script. When I run sync_ratings.py a new window opens and closes very quickly...I have edited the config with my settings, but tbh I have no idea I've done that correctly eg. line one is: #server = #Elvidge+
> 
> Thank you for your patience!

open a command prompt then run the command so that you can see the output.

**Comment by Paulus237** [comment]
That's the issue, a new window opens and closes quickly. In the cmd window it just moves down a line.
<img width="577" alt="Screenshot 2024-04-16 202321" src="https://github.com/patzm/plex-music-rating-sync/assets/114867772/a3e74d9e-f6a8-47bf-b5b0-8e06ca2d017f">

**Comment by smilerz** [comment]
the correct command is `python sync_ratings.py ...`

**Comment by Paulus237** [comment]
Thanks, simple!! OK that's done and I needed to install fuzzywuzzy...done.
Brilliant - It's working!!!
I've had to manually add server and username in the command line. What is the correct layout in the config file?
Incl. the right argument for synching playlists? "--sync [playlists]"

PS. A big thank you - I now have my ratings in Plex

**Comment by Paulus237** [comment]
PS. A big thank you - I now have my ratings in Plex

**Comment by Paulus237** [comment]
I think I've fixed it - it should be --sync PLAYLISTS

This now gives me:   AttributeError: 'PlexSync' object has no attribute 'local_player'

**Comment by patzm** [comment]
please always post the full command you are running.
Also carefully read [the command help](https://github.com/patzm/plex-music-rating-sync?tab=readme-ov-file#how-to-run). To make sure, read it again 😆. Even for experienced programmers, it is common to over read something and then suddenly everything makes sense 😉.
