### ISSUE TITLE
ERROR: No matching distribution found for pywin32>=223 (from pypiwin32->-r requirements.txt (line 3))

### ISSUE THREAD

**Issue by rollecode** [patzm/plex-music-rating-sync#5]
Using Fedora 31.

```
[11:39:39] rolle plex-music-rating-sync $ sudo pip3.6 install -r requirements.txt
Collecting PlexAPI>=3.0.6
  Downloading PlexAPI-3.6.0.tar.gz (87 kB)
     |████████████████████████████████| 87 kB 1.1 MB/s 
Collecting fuzzywuzzy
  Using cached fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Collecting pypiwin32
  Using cached pypiwin32-223-py3-none-any.whl (1.7 kB)
Collecting numpy
  Downloading numpy-1.18.4-cp36-cp36m-manylinux1_x86_64.whl (20.2 MB)
     |████████████████████████████████| 20.2 MB 18.5 MB/s 
Collecting requests
  Downloading requests-2.23.0-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 1.6 MB/s 
ERROR: Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32->-r requirements.txt (line 3)) (from versions: none)
ERROR: No matching distribution found for pywin32>=223 (from pypiwin32->-r requirements.txt (line 3))
```

**Comment by patzm** [comment]
I am not sure what you wanted to achieve :smile: This tool was made for syncing MediaMonkey libraries to Plex. Hence, it is local to Windows. You use Fedora, Linux.

**Comment by rollecode** [comment]
Oh. Just blindly followed instructions, thought this is a command line tool for syncing plex ratings in general, sorry! The repository name is "plex-music-rating-sync" and the description is "Plex Agents do not read music ratings when importing music files. This project aims to provide a sync tool". Even the further description in README does not mention MediaMonkey anywhere until just requirements. Maybe you should clarify it a bit to prevent confusion? :) Anyway, searching for a tool to backup or sync my plex music ratings and/or playcounts as I lost them last time I reinstalled my server.

**Comment by patzm** [comment]
I think the _Features_ and _Requirements_ sections are pretty clear on that. I don't think this should go in the general description.
Feel free to extend this tool and file a PR. It is trivial to make `pywin32` and Windows-only dependency.
