### ISSUE TITLE
providing a password as a CLI argument confuses servername and username

### ISSUE THREAD

**Issue by patzm** [patzm/plex-music-rating-sync#6]
I believe I have everything set up, but when I try to sync from the command prompt, I receive the following message:
```
INFO: Connecting to the Plex with username “XXX”
[10:15:35] WARNING [PlexSync.PlexPlayer.connect:213] Failed to connect: (401) unauthorized; https://plex.tv/users/sign_in.xml <?xml version="1.0" encoding="UTF-8"?> You appear to be having trouble signing in to an account. You may wish to try resetting your password at https://plex.tv/reset
[10:15:36] WARNING [PlexSync.PlexPlayer.connect:213] Failed to connect: (401) unauthorized; https://plex.tv/users/sign_in.xml <?xml version="1.0" encoding="UTF-8"?> You appear to be having trouble signing in to an account. You may wish to try resetting your password at https://plex.tv/reset
[10:15:38] WARNING [PlexSync.PlexPlayer.connect:213] Failed to connect: (401) unauthorized; https://plex.tv/users/sign_in.xml <?xml version="1.0" encoding="UTF-8"?> You appear to be having trouble signing in to an account. You may wish to try resetting your password at https://plex.tv/reset
[10:15:38] ERROR [PlexSync.PlexPlayer.connect:216] Exiting after 3 failed attempts …
```
where the username it tries to use was actually what I put as the server name. Do you have any suggestions on how I might fix this?

**Comment by patzm** [comment]
Let's try to get to the bottom of this:
* This could be a simple command line problem. Can you post how you invoke the tool? Please make sure to **remove sensitive information**!
* Is the user you are trying to log in with the Plex _owner_? I.e. of the Plex server?

**Comment by marshie250** [comment]
Hi! Sorry for taking so long--I used an old email that I don't check very much. Thank you for getting back to me! This is the command I use:
```bash
sync_ratings.py --passwd PasswordTakenOut --server ServerNameTakenOut --username UserNameTakenOut --player MediaMonkey
```

And yes, I am using the owner log in.

**Comment by patzm** [comment]
ok, can you try passing the arguments with `--arg="value"`? I.e. with an `=` sign between key and value and by quoting the _value_ with double quotes `"`. I believe that your password has characters that are interpreted differently by `bash` _before_ the Python script gets a chance to look at them.

**Comment by marshie250** [comment]
OK, I tried this:
sync_ratings.py --passwd="Passwordtakenout"  --server="Servertakenout" --username="untakenout" --player="MediaMonkey"

and received the same errors.
 I am still seeing this:

INFO: Connecting to the Plex with username “XXX”

where XXX is the server name, not the username.

**Comment by patzm** [comment]
Ok, I looked at the relevant code now. Quite messy :laughing:. I implemented something that might fix it. Hence, can you try either of the following two things:
1. Try the fix by checking out the branch [`martin/fix/6`](https://github.com/patzm/plex-music-rating-sync/tree/martin/fix/6) and running the same thing again.
1. Do not provide the password on the command line, i.e. omit `--passwd` and wait for the program to ask you for it. I think this circumvents the bug.

**Comment by marshie250** [comment]
Thanks for the reply! I ended up nuking everything, reinstalling Python and all of its requirements, and using the quotation marks as you suggested. It seems to be working now! Not sure if it was the fix or the reinstall though.

**Comment by patzm** [comment]
ok, but just to confirm: you ended up using the branch? If yes, I will just assume that either that fixed it or that it was invalid in the first place :laughing: :man_shrugging:. Also, if you were still using the CLI-argument-way to feed the password, then these changes didn't break that either.
