### ISSUE TITLE
Rating mismatches

### ISSUE THREAD

**Issue by mradrianmarsh** [patzm/plex-music-rating-sync#7]
Hi,

I thought I'd try this script out against a Test collection, just one album on the PLEX side and see what happened.

I started by:
Cleaning all the Ratings from the folder in PLEX
Cleaning all the Ratings on the folder in MM.
Setting one file to 5stars in MM
Syncing the tags between MM and the files.

Then ran the script.

It did match up the 5star test file I'd set, but it also set some other MP3s in PLEX to 2star and 3star, which aren't set in MM.

Whats the threshold it uses to commit to the update ?
When I look at the debug log for one of the wrong files:

	Line 851: [16:38:59] DEBUG: Found match with score 35.0 for Dido - No Angel - Hunter: Adam Carroll - Lookin' Out the Screen Door - Hunter's Song
	Line 5487: [16:41:50] DEBUG: Updating rating of track "Adam Carroll - Lookin' Out the Screen Door - Hunter's Song" to 3.0 stars

So I think its matching Dido there to Adam Carroll?

I'll look through the code next to see if I can spot a threshold value variable

**Comment by mradrianmarsh** [comment]
What I would add, just in case its not clear above,  whilst theres just the one test folder in Plex, it clearly is looking across the whole library in MM.  I've taken DB backups in both Plex and MM just in case.

I was trying to work out if the updates were uni or bi directional.

**Comment by patzm** [comment]
Hi @mradrianmarsh,
> I was trying to work out if the updates were uni or bi directional.

Only one-directional, MM > Plex. It would not be hard to implement bi-directional sync, but I don't plan to do this. For me, it was a 1-time sync :laughing:. Contributions are welcome though.

> Whats the threshold it uses to commit to the update?

Don't remember, but I think it was unit-less anyways. Maybe exposing the threshold is the right way to go. Or preventing that one file on the source side (your single folder / album) can match multiple destination tracks. That's is nonsense if it behaves like this. I always only debugged in a setting where both source and target have indexed the same music library. Again, contributions welcome.

Maybe you can try syncing in a setting where source and target have matching libraries. Note, that there is the flag `--dry` which only prints what would have been done, but without actually changing something.

**Comment by mradrianmarsh** [comment]
This setup above was really just for testing.. to make sure that when I applied it, it wasn't going to write back to the physical files, and so I could see what it did to the MM db.  So knowing its MM >> PLEX unidirectional is a great help because my PLEX ratings are basically empty anyway, so I could always blow those away.

When the logs were showing me a %match-certainty, I thought that was maybe its way of telling me how sure it was about the match.  I've no experience with python so maybe this is my way in to learn a bit.

So what I'll do is in my spare time I'll do a dry run of like for like libraries and then see if I can grep the file for what would be updated and do some analysis.  In MM I split the libraries out and there may not be a natural fit I guess, but I think I could create some PLEX libraries to match as close as I can and test.  It'll likely take a while to play around, and hope you don't mind if I ask some questions up.

Originally I was really hoping that PLEX would bring in a feature to write ratings back to the files, and it was only reading your threads leading me here that made me realise why they probably don't (multi user support), so just to say - THANKYOU for writing and sharing this so far, it'll likely at least get me partially there and then make PLEX more useful whilst making MM and the files stay as my main truth.

**Comment by patzm** [comment]
> When the logs were showing me a %match-certainty, I thought that was maybe its way of telling me how sure it was about the match. I've no experience with python so maybe this is my way in to learn a bit.

Yes you are right about that. The matching certainty (or `score` in the code) is a measure of confidence. The threshold is hard-coded to `30` here: https://github.com/patzm/plex-music-rating-sync/blob/d25062501c772623465c724593e5870dd9325247/sync_pair.py#L89

The `score`, which is compared against the threshold is calculated here: https://github.com/patzm/plex-music-rating-sync/blob/d25062501c772623465c724593e5870dd9325247/sync_pair.py#L130-L140

You can see that I use fuzzy matching for the metadata. So the threshold `30` and the `score` are truely unit-less. It simply means: the more the better.

> hope you don't mind if I ask some questions up.

of course not :wink:. I hope I can answer quickly.

**Comment by smilerz** [comment]
i think this can be closed now

**Comment by patzm** [comment]
cool thx, @smilerz you can use GitHubs automatic linking between PRs and issues ([link](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)). I updated your PR description accordingly, as an example :wink:
