### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by harvey721** [patzm/plex-music-rating-sync#8]
Complete newb here: 
I managed to install git, python, pip,....etc and I tried running the program but I'm getting the following error :

"Traceback (most recent call last):
  File "D:\Downloads\Applications\plex-music-rating-sync\sync_ratings.py", line 8, in <module>
    from sync_pair import *
  File "D:\Downloads\Applications\plex-music-rating-sync\sync_pair.py", line 3, in <module>
    from fuzzywuzzy import fuzz
ModuleNotFoundError: No module named 'fuzzywuzzy'"

**Comment by patzm** [comment]
can you try to install to run in the root of the repository
```bash
pip install -r requirements.txt
```
You are missing requirements. Check https://github.com/patzm/plex-music-rating-sync#requirements and https://github.com/patzm/plex-music-rating-sync#installation

**Comment by harvey721** [comment]
I followed the instructions and it seems the module was installed. Attached is what I got when I ran the command.
[pip install.txt](https://github.com/patzm/plex-music-rating-sync/files/5566167/pip.install.txt)

**Comment by harvey721** [comment]
Update: finally got it to run in powershell but now I'm getting this:

./sync_ratings.py [--dry] [--log LOG] --server <Dxxx> --username <hxxx|hxxx> --player MediaMonkey
At line:1 char:48
+ ./sync_ratings.py [--dry] [--log LOG] --server <DS220> --username <ha ...
+                                                ~
The '<' operator is reserved for future use.
At line:1 char:67
+ ... _ratings.py [--dry] [--log LOG] --server <DS220> --username <harvey21 ...
+                                                                 ~
The '<' operator is reserved for future use.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RedirectionNotSupported

**Comment by patzm** [comment]
don't enclose your username with `<>`. This simply indicates a placeholder.

**Comment by harvey721** [comment]
Does the Plex server need to be running on the same machine? I have my Plex library on my NAS.

**Comment by patzm** [comment]
No it doesn't. I only must be reachable.

**Comment by harvey721** [comment]
I must be doing something wrong. I ran the command and nothing happens. no error messages, rating not updated.
This is what I'm running from powershell:
./sync_ratings.py --server DS220 --username hxxxxx@gmail.com --player MediaMonkey

**Comment by patzm** [comment]
maybe turn up the logging verbosity?

**Comment by harvey721** [comment]
I tried with this as well but nothing happened:
./sync_ratings.py [--dry] [--log LOG] --server DS220 --username hxxxxx --player MediaMonkey

**Comment by patzm** [comment]
:see_no_evil: oh boy, much to learn :laughing: the brackets `[]` only indicate that these are optional arguments. The captial `LOG` indicates you can put a value there, in this case the logging verbosity. Try
```bash
 ./sync_ratings.py --dry --log DEBUG --server DS220 --username hxxxxx --player MediaMonkey
```
See https://github.com/patzm/plex-music-rating-sync#how-to-run for reference, there are actually these examples.

**Comment by harvey721** [comment]
I had tried earlier without the brackets but got the same result. Is it supposed to write a log file somewhere?
sorry for all the questions. I'm not sure why Plex can't import ratings from the files when scanning. It's very frustrating.

**Comment by patzm** [comment]
It should print that to the command line. I think you are doing something else very wrong. I even doubt you are running the program... can you try to run it like this:
```bash
python3 sync_ratings.py ...
```
`...` is the rest like you had it before.

As per why plex can't import ratings: this actually is necessary. Plex supports multiple users. All share the same music files. That presents you with a dilemma: should all users share the same imported ratings? Probably not, they are something very personal. So opting for not importing them is probably a very reasonable choice.

**Comment by harvey721** [comment]
Just tried again and didn't get anything. I'm sure I'm doing something wrong but I don't know what it is.
I agree with you that every user should have a choice in their ratings but they should at least give us the option of importing the ratings. I have thousands of music files that are rated and there's no way I will spend hours rerating these. They also don't import playlists so there's no easy workaround for this issue.

**Comment by patzm** [comment]
Yes true, ratings are also equally _personal_. I think I once thought about implementing this here. Contributions welcome :smile:. Anyways, I believe your problems are more related to how you use the CLI and your environment. I am closing the issue now.
